package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AllowanceRate generated by hbm2java
 */
@Entity
@Table(name = "allowance_rate")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class AllowanceRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1219669161067656635L;
	private Long id;
	private UsState usState;
	private AllowanceType allowanceType;
	private BigDecimal amount;
	private Date dateOfEntry;
	private Date wef;
	private Date releaseDate;

	public AllowanceRate() {
	}

	public AllowanceRate(UsState usState, AllowanceType allowanceType) {
		this.usState = usState;
		this.allowanceType = allowanceType;
	}

	public AllowanceRate(UsState usState, AllowanceType allowanceType, BigDecimal amount,
			Date dateOfEntry, Date wef, Date releaseDate) {
		this.usState = usState;
		this.allowanceType = allowanceType;
		this.amount = amount;
		this.dateOfEntry = dateOfEntry;
		this.wef = wef;
		this.releaseDate = releaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_state_id")
	public UsState getUsState() {
		return this.usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allowance_type_id")
	public AllowanceType getAllowanceType() {
		return this.allowanceType;
	}

	public void setAllowanceType(AllowanceType allowanceType) {
		this.allowanceType = allowanceType;
	}

	@Column(name = "amount", precision = 10, scale = 2)
	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("AllowanceRate [id=");
		builder.append(id);
		builder.append(", usState=");
		builder.append(usState);
		builder.append(", allowanceType=");
		builder.append(allowanceType.getId());
		builder.append(", amount=");
		builder.append(amount);
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", wef=");
		builder.append(wef);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append("]");
		return builder.toString();
	}

}
