package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "batch_detail")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class BatchDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8948505937652998534L;

	private Long id;
	private String batchNo;
	private Payroll payroll;
	private BatchType batchType;
	private Date scheduledDate;
	private Date processedDate;
	private Date cancelledDate;
	private TransactionBody transactionBody;
	private String description;
	private Status status;

	public enum Status {
		SCHEDULED("Scheduled"), //
		PROCESSED("Processed"), //
		CANCELLED("Cancelled"); //

		private String name;

		private Status(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public enum BatchType {
		FUND_RELATED("Fund Related"), //
		NON_FUND_RELATED("Non-Fund Related"); //

		private String name;

		private BatchType(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public BatchDetail() {
	}

	public BatchDetail(String batchNo, Payroll payroll, BatchType batchType, Date scheduledDate,
			Date processedDate, Date cancelledDate, TransactionBody transactionBody,
			String description, Status status) {
		super();
		this.batchNo = batchNo;
		this.payroll = payroll;
		this.batchType = batchType;
		this.scheduledDate = scheduledDate;
		this.processedDate = processedDate;
		this.cancelledDate = cancelledDate;
		this.transactionBody = transactionBody;
		this.description = description;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "batch_no", unique = true, length = 30)
	public String getBatchNo() {
		return batchNo;
	}

	public void setBatchNo(String batchNo) {
		this.batchNo = batchNo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payroll_id")
	public Payroll getPayroll() {
		return this.payroll;
	}

	public void setPayroll(Payroll payroll) {
		this.payroll = payroll;
	}

	@Column(name = "batch_type")
	public BatchType getBatchType() {
		return batchType;
	}

	public void setBatchType(BatchType batchType) {
		this.batchType = batchType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "scheduled_date", length = 19)
	public Date getScheduledDate() {
		return scheduledDate;
	}

	public void setScheduledDate(Date scheduledDate) {
		this.scheduledDate = scheduledDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "processed_date", length = 19)
	public Date getProcessedDate() {
		return processedDate;
	}

	public void setProcessedDate(Date processedDate) {
		this.processedDate = processedDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cancelled_date", length = 19)
	public Date getCancelledDate() {
		return cancelledDate;
	}

	public void setCancelledDate(Date cancelledDate) {
		this.cancelledDate = cancelledDate;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "transaction_body_id")
	public TransactionBody getTransactionBody() {
		return transactionBody;
	}

	public void setTransactionBody(TransactionBody transactionBody) {
		this.transactionBody = transactionBody;
	}

	@Column(name = "description", length = 500)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "status")
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

}
