package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompanyPayrollDeduction generated by hbm2java
 */
@Entity
@Table(name = "company_payroll_deduction")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CompanyPayrollDeduction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7299956116183626785L;
	private Long id;
	private CompanyDeduction companyDeduction;
	private EmployeePayroll employeePayroll;
	private BigDecimal value;

	public CompanyPayrollDeduction() {
	}

	public CompanyPayrollDeduction(CompanyDeduction companyDeduction,
			EmployeePayroll employeePayroll, BigDecimal value) {
		this.companyDeduction = companyDeduction;
		this.employeePayroll = employeePayroll;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_deduction_id")
	public CompanyDeduction getCompanyDeduction() {
		return this.companyDeduction;
	}

	public void setCompanyDeduction(CompanyDeduction companyDeduction) {
		this.companyDeduction = companyDeduction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_payroll_id")
	public EmployeePayroll getEmployeePayroll() {
		return this.employeePayroll;
	}

	public void setEmployeePayroll(EmployeePayroll employeePayroll) {
		this.employeePayroll = employeePayroll;
	}

	@Column(name = "value", precision = 10, scale = 2)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyPayrollDeduction [id=");
		builder.append(id);
		builder.append(", companyDeduction=");
		builder.append(companyDeduction.getId());
		builder.append(", employeePayroll=");
		builder.append(employeePayroll.getId());
		builder.append(", value=");
		builder.append(value);
		builder.append("]");
		return builder.toString();
	}

}
