package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompanyEarning generated by hbm2java
 */
@Entity
@Table(name = "company_earning")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CompanyEarning implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9175423460342136764L;
	private Long id;
	private Company company;
	private Earning earning;
	private String displayName;
	private Set<EmployeeEarning> employeeEarnings = new HashSet<EmployeeEarning>(0);
	private Set<CompanyPaidBenefit> companyPaidBenefits = new HashSet<CompanyPaidBenefit>(0);

	public CompanyEarning() {
	}

	public CompanyEarning(Long id, String displayName) {
		this.id = id;
		this.displayName = displayName;
	}

	public CompanyEarning(Company company, Earning earning) {
		this.company = company;
		this.earning = earning;
	}

	public CompanyEarning(Company company, Earning earning, String displayName,
			Set<EmployeeEarning> employeeEarnings, Set<CompanyPaidBenefit> companyPaidBenefits) {
		this.company = company;
		this.earning = earning;
		this.displayName = displayName;
		this.employeeEarnings = employeeEarnings;
		this.companyPaidBenefits = companyPaidBenefits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "earning_id")
	public Earning getEarning() {
		return this.earning;
	}

	public void setEarning(Earning earning) {
		this.earning = earning;
	}

	@Column(name = "display_name", length = 45)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(String displayName) {
		this.displayName = displayName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyEarning", cascade = CascadeType.ALL)
	public Set<EmployeeEarning> getEmployeeEarnings() {
		return this.employeeEarnings;
	}

	public void setEmployeeEarnings(Set<EmployeeEarning> employeeEarnings) {
		this.employeeEarnings = employeeEarnings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyEarning")
	public Set<CompanyPaidBenefit> getCompanyPaidBenefits() {
		return this.companyPaidBenefits;
	}

	public void setCompanyPaidBenefits(Set<CompanyPaidBenefit> companyPaidBenefits) {
		this.companyPaidBenefits = companyPaidBenefits;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyEarning [id=");
		builder.append(id);
		builder.append(", company=");
		builder.append(company.getId());
		builder.append(", earning=");
		builder.append(earning.getId());
		builder.append(", displayName=");
		builder.append(displayName);
		builder.append("]");
		return builder.toString();
	}

}
