package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CompanyPayrollDeduction generated by hbm2java
 */
@Entity
@Table(name = "company_payroll_worker_comp ")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CompanyPayrollWorkerComp implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3007199101671264497L;
	private Long id;
	private CompanyWorkerCompensation companyWorkerCompensation;
	private EmployeePayroll employeePayroll;
	private BigDecimal value;

	public CompanyPayrollWorkerComp() {
	}

	public CompanyPayrollWorkerComp(CompanyWorkerCompensation companyWorkerCompensation,
			EmployeePayroll employeePayroll, BigDecimal value) {
		this.companyWorkerCompensation = companyWorkerCompensation;
		this.employeePayroll = employeePayroll;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_worker_compensation_id")
	public CompanyWorkerCompensation getCompanyWorkerCompensation() {
		return companyWorkerCompensation;
	}

	public void setCompanyWorkerCompensation(CompanyWorkerCompensation companyWorkerCompensation) {
		this.companyWorkerCompensation = companyWorkerCompensation;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_payroll_id")
	public EmployeePayroll getEmployeePayroll() {
		return this.employeePayroll;
	}

	public void setEmployeePayroll(EmployeePayroll employeePayroll) {
		this.employeePayroll = employeePayroll;
	}

	@Column(name = "value", precision = 10, scale = 2)
	public BigDecimal getValue() {
		return this.value;
	}

	public void setValue(BigDecimal value) {
		this.value = value;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyPayrollWorkerComp [id=");
		builder.append(id);
		builder.append(", companyWorkerCompensation=");
		builder.append(companyWorkerCompensation.getId());
		builder.append(", employeePayroll=");
		builder.append(employeePayroll.getId());
		builder.append(", value=");
		builder.append(value);
		builder.append("]");
		return builder.toString();
	}

}
