package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnoreProperties;

/**
 * CompanyWorkerCompensation generated by hbm2java
 */
@Entity
@Table(name = "company_worker_compensation")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
@JsonIgnoreProperties({ "workersCompensationTaxRates", "usState", "employees", "company" })
public class CompanyWorkerCompensation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4605421179164454090L;
	private Long id;
	private UsState usState;
	private Company company;
	private String code;
	private String description;
	private Set<WorkersCompensationTaxRate> workersCompensationTaxRates = new HashSet<WorkersCompensationTaxRate>(
			0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public CompanyWorkerCompensation() {
	}

	public CompanyWorkerCompensation(UsState usState, Company company, String code) {
		this.usState = usState;
		this.company = company;
		this.code = code;
	}

	public CompanyWorkerCompensation(UsState usState, Company company, String code,
			String description, Set<WorkersCompensationTaxRate> workersCompensationTaxRates,
			Set<Employee> employees) {
		this.usState = usState;
		this.company = company;
		this.code = code;
		this.description = description;
		this.workersCompensationTaxRates = workersCompensationTaxRates;
		this.employees = employees;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_state_id")
	public UsState getUsState() {
		return this.usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "code", length = 45)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyWorkerCompensation")
	public Set<WorkersCompensationTaxRate> getWorkersCompensationTaxRates() {
		return this.workersCompensationTaxRates;
	}

	public void setWorkersCompensationTaxRates(
			Set<WorkersCompensationTaxRate> workersCompensationTaxRates) {
		this.workersCompensationTaxRates = workersCompensationTaxRates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyWorkerCompensation")
	public Set<Employee> getEmployees() {
		return employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyWorkerCompensation [id=");
		builder.append(id);
		builder.append(", usState=");
		builder.append(usState.getId());
		builder.append(", company=");
		builder.append(company.getId());
		builder.append(", code=");
		builder.append(code);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
