package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CompanyTax generated by hbm2java
 */
@Entity
@Table(name = "company_tax")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CompanyTax implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1605908158245913518L;
	private Long id;
	private TaxType taxType;
	private Company company;
	private TaxDepositCycle taxDepositCycle;
	private Boolean exempted;
	private String ein;

	private Set<CompanyPayrollTax> companyPayrollTaxes = new HashSet<CompanyPayrollTax>(0);

	public CompanyTax() {
	}

	public CompanyTax(TaxType taxType, TaxDepositCycle taxDepositCycle, Company company,
			String ein, Boolean exempted) {
		this.taxType = taxType;
		this.taxDepositCycle = taxDepositCycle;
		this.company = company;
		this.ein = ein;
		this.exempted = exempted;

	}

	public CompanyTax(TaxType taxType, TaxDepositCycle taxDepositCycle, Company company,
			String ein, Boolean exempted, Set<CompanyPayrollTax> companyPayrollTaxes) {
		this.taxType = taxType;
		this.taxDepositCycle = taxDepositCycle;
		this.company = company;
		this.ein = ein;
		this.exempted = exempted;
		this.companyPayrollTaxes = companyPayrollTaxes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_type_id")
	public TaxType getTaxType() {
		return this.taxType;
	}

	public void setTaxType(TaxType taxType) {
		this.taxType = taxType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_deposit_cycle_id")
	public TaxDepositCycle getTaxDepositCycle() {
		return this.taxDepositCycle;
	}

	public void setTaxDepositCycle(TaxDepositCycle taxDepositCycle) {
		this.taxDepositCycle = taxDepositCycle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "ein", length = 45)
	public String getEin() {
		return this.ein;
	}

	public void setEin(String ein) {
		this.ein = ein;
	}

	@Column(name = "exempted")
	public Boolean isExempted() {
		return this.exempted;
	}

	public void setExempted(Boolean exempted) {
		this.exempted = exempted;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "companyTax")
	public Set<CompanyPayrollTax> getCompanyPayrollTaxes() {
		return this.companyPayrollTaxes;
	}

	public void setCompanyPayrollTaxes(Set<CompanyPayrollTax> companyPayrollTaxes) {
		this.companyPayrollTaxes = companyPayrollTaxes;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyTax [id=");
		builder.append(id);
		builder.append(", taxType=");
		builder.append(taxType.getId());
		builder.append(", company=");
		builder.append(company.getId());
		builder.append(", taxDepositCycle=");
		builder.append(taxDepositCycle.getId());
		builder.append(", exempted=");
		builder.append(exempted);
		builder.append(", ein=");
		builder.append(ein);
		builder.append("]");
		return builder.toString();
	}

}
