package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyFeature generated by hbm2java
 */
@Entity
@Table(name = "company_feature")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CompanyFeature implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7998824091609912404L;

	public enum Status {
		ACTIVATED("Activated"), DEACTIVATED("DeActivated");
		private String name;

		private Status(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	private Long id;
	private PlanFeature planFeature;
	private Company company;
	private Status status;
	private Date activatedOn;
	private Date deactivatedOn;

	public CompanyFeature() {
	}

	public CompanyFeature(PlanFeature planFeature, Company company) {
		this.planFeature = planFeature;
		this.company = company;
	}

	public CompanyFeature(PlanFeature planFeature, Company company, Status status,
			Date activatedOn, Date deactivatedOn) {
		this.planFeature = planFeature;
		this.company = company;
		this.status = status;
		this.activatedOn = activatedOn;
		this.deactivatedOn = deactivatedOn;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "plan_feature_id")
	public PlanFeature getPlanFeature() {
		return planFeature;
	}

	public void setPlanFeature(PlanFeature planFeature) {
		this.planFeature = planFeature;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "status", length = 20)
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "activated_on", length = 19)
	public Date getActivatedOn() {
		return this.activatedOn;
	}

	public void setActivatedOn(Date activatedOn) {
		this.activatedOn = activatedOn;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "deactivated_on", length = 19)
	public Date getDeactivatedOn() {
		return this.deactivatedOn;
	}

	public void setDeactivatedOn(Date deactivatedOn) {
		this.deactivatedOn = deactivatedOn;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CompanyFeature [id=");
		builder.append(id);
		builder.append(", planService=");
		builder.append(planFeature.getId());
		builder.append(", company=");
		builder.append(company.getId());
		builder.append(", status=");
		builder.append(status);
		builder.append(", activatedOn=");
		builder.append(activatedOn);
		builder.append(", deactivatedOn=");
		builder.append(deactivatedOn);
		builder.append("]");
		return builder.toString();
	}

}
