package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CountyTaxRate generated by hbm2java
 */
@Entity
@Table(name = "county_tax_rate")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class CountyTaxRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4439348707135237075L;
	private Long id;
	private ResidentStatus residentStatus;
	private TaxType taxType;
	private UsCounty usCounty;
	private BigDecimal rate;
	private BigDecimal ceiling;
	private Date dateOfEntry;
	private Date wef;
	private Date releaseDate;

	public enum ResidentStatus {
		RESIDENT("Resident"), NON_RESIDENT("Non Resident");
		private String name;

		private ResidentStatus(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public CountyTaxRate() {
	}

	public CountyTaxRate(ResidentStatus residentStatus, TaxType taxType, UsCounty usCounty) {
		this.residentStatus = residentStatus;
		this.taxType = taxType;
		this.usCounty = usCounty;
	}

	public CountyTaxRate(ResidentStatus residentStatus, TaxType taxType, UsCounty usCounty,
			BigDecimal rate, BigDecimal ceiling, Date dateOfEntry, Date wef, Date releaseDate) {
		this.residentStatus = residentStatus;
		this.taxType = taxType;
		this.usCounty = usCounty;
		this.rate = rate;
		this.ceiling = ceiling;
		this.dateOfEntry = dateOfEntry;
		this.wef = wef;
		this.releaseDate = releaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "resident_status")
	public ResidentStatus getResidentStatus() {
		return this.residentStatus;
	}

	public void setResidentStatus(ResidentStatus residentStatus) {
		this.residentStatus = residentStatus;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_type_id")
	public TaxType getTaxType() {
		return this.taxType;
	}

	public void setTaxType(TaxType taxType) {
		this.taxType = taxType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_county_id")
	public UsCounty getUsCounty() {
		return this.usCounty;
	}

	public void setUsCounty(UsCounty usCounty) {
		this.usCounty = usCounty;
	}

	@Column(name = "rate", precision = 7, scale = 2)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "ceiling", precision = 10, scale = 2)
	public BigDecimal getCeiling() {
		return this.ceiling;
	}

	public void setCeiling(BigDecimal ceiling) {
		this.ceiling = ceiling;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("CountyTaxRate [id=");
		builder.append(id);
		builder.append(", residentStatus=");
		builder.append(residentStatus);
		builder.append(", taxType=");
		builder.append(taxType.getId());
		builder.append(", usCounty=");
		builder.append(usCounty.getId());
		builder.append(", rate=");
		builder.append(rate);
		builder.append(", ceiling=");
		builder.append(ceiling);
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", wef=");
		builder.append(wef);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append("]");
		return builder.toString();
	}

}
