package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.codehaus.jackson.annotate.JsonManagedReference;
import org.codehaus.jackson.map.annotate.JsonSerialize;

/**
 * Deduction generated by hbm2java
 */
@Entity
@Table(name = "deduction", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"deduction_category_id", "deduction_name" }) })
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
// @JsonIgnoreProperties({ "companyDeductions" })
public class Deduction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4456616220012440290L;
	private Long id;
	private DeductionCategory deductionCategory;
	private String deductionName;
	private String description;
	@JsonManagedReference
	private Set<CompanyDeduction> companyDeductions = new HashSet<CompanyDeduction>(0);

	public Deduction() {
	}

	public Deduction(DeductionCategory deductionCategory, String deductionName) {
		this.deductionCategory = deductionCategory;
		this.deductionName = deductionName;
	}

	public Deduction(DeductionCategory deductionCategory, String deductionName, String description,
			Set<CompanyDeduction> companyDeductions) {
		this.deductionCategory = deductionCategory;
		this.deductionName = deductionName;
		this.description = description;
		this.companyDeductions = companyDeductions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@JsonBackReference("deductionCategory-deduction")
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "deduction_category_id")
	@JsonSerialize
	public DeductionCategory getDeductionCategory() {
		return this.deductionCategory;
	}

	public void setDeductionCategory(DeductionCategory deductionCategory) {
		this.deductionCategory = deductionCategory;
	}

	@Column(name = "deduction_name", length = 45)
	public String getDeductionName() {
		return this.deductionName;
	}

	public void setDeductionName(String deductionName) {
		this.deductionName = deductionName;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@JsonManagedReference("deduction-companyDeduction")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deduction")
	public Set<CompanyDeduction> getCompanyDeductions() {
		return this.companyDeductions;
	}

	public void setCompanyDeductions(Set<CompanyDeduction> companyDeductions) {
		this.companyDeductions = companyDeductions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Deduction [id=");
		builder.append(id);
		builder.append(", deductionCategory=");
		builder.append(deductionCategory.getId());
		builder.append(", deductionName=");
		builder.append(deductionName);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
