package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * DeductionCategory generated by hbm2java
 */
@Entity
@Table(name = "deduction_category")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
// @JsonIgnoreProperties({ "deductions" })
public class DeductionCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6603907558095175748L;
	private Long id;
	private String category;
	private String description;
	private Set<Deduction> deductions = new HashSet<Deduction>(0);

	public DeductionCategory() {
	}

	public DeductionCategory(String category) {
		this.category = category;
	}

	public DeductionCategory(String category, String description, Set<Deduction> deductions) {
		this.category = category;
		this.description = description;
		this.deductions = deductions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "category", length = 45, unique = true)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@JsonManagedReference("deductionCategory-deduction")
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "deductionCategory")
	public Set<Deduction> getDeductions() {
		return this.deductions;
	}

	public void setDeductions(Set<Deduction> deductions) {
		this.deductions = deductions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeductionCategory [id=");
		builder.append(id);
		builder.append(", category=");
		builder.append(category);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
