package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TypedeductionCap generated by hbm2java
 */
@Entity
@Table(name = "deduction_cap")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class DeductionCap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7524703197484388438L;
	private Long id;
	private CompanyDeduction companyDeduction;
	private UsState usState;
	private BigDecimal capAmount;
	private Date dateOfEntry;
	private Date wef;
	private Date releaseDate;

	public DeductionCap() {
	}

	public DeductionCap(CompanyDeduction companyDeduction, UsState usState) {
		this.companyDeduction = companyDeduction;
		this.usState = usState;
	}

	public DeductionCap(CompanyDeduction companyDeduction, UsState usState, BigDecimal capAmount,
			Date dateOfEntry, Date wef, Date releaseDate) {
		this.companyDeduction = companyDeduction;
		this.usState = usState;
		this.capAmount = capAmount;
		this.dateOfEntry = dateOfEntry;
		this.wef = wef;
		this.releaseDate = releaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_deduction_id")
	public CompanyDeduction getCompanyDeduction() {
		return this.companyDeduction;
	}

	public void setCompanyDeduction(CompanyDeduction companyDeduction) {
		this.companyDeduction = companyDeduction;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_state_id")
	public UsState getUsState() {
		return this.usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@Column(name = "cap_amount", precision = 10, scale = 2)
	public BigDecimal getCapAmount() {
		return this.capAmount;
	}

	public void setCapAmount(BigDecimal capAmount) {
		this.capAmount = capAmount;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DeductionCap [id=");
		builder.append(id);
		builder.append(", companyDeduction=");
		builder.append(companyDeduction.getId());
		builder.append(", usState=");
		builder.append(usState);
		builder.append(", capAmount=");
		builder.append(capAmount);
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", wef=");
		builder.append(wef);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append("]");
		return builder.toString();
	}

}
