package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * EarningCategory generated by hbm2java
 */
@Entity
@Table(name = "earning_category")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class EarningCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2316342592754569791L;
	private Long id;
	private String category;
	private String description;
	private Set<Earning> earnings = new HashSet<Earning>(0);

	public EarningCategory() {
	}

	public EarningCategory(String category) {
		this.category = category;
	}

	public EarningCategory(String category, String description, Set<Earning> earnings) {
		this.category = category;
		this.description = description;
		this.earnings = earnings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "category", length = 45, unique = true)
	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "earningCategory")
	public Set<Earning> getEarnings() {
		return this.earnings;
	}

	public void setEarnings(Set<Earning> earnings) {
		this.earnings = earnings;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("EarningCategory [id=");
		builder.append(id);
		builder.append(", category=");
		builder.append(category);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
