package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Earning generated by hbm2java
 */
@Entity
@Table(name = "earning", uniqueConstraints = { @UniqueConstraint(columnNames = {
		"earning_category_id", "earning_name" }) })
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Earning implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5619071732117470730L;
	private Long id;
	private EarningCategory earningCategory;
	private String earningName;
	private String description;
	private Set<CompanyEarning> companyEarnings = new HashSet<CompanyEarning>(0);

	public Earning() {
	}

	public Earning(EarningCategory earningCategory, String earningName) {
		this.earningCategory = earningCategory;
		this.earningName = earningName;
	}

	public Earning(EarningCategory earningCategory, String earningName, String description,
			Set<CompanyEarning> companyEarnings) {
		this.earningCategory = earningCategory;
		this.earningName = earningName;
		this.description = description;
		this.companyEarnings = companyEarnings;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "earning_category_id")
	public EarningCategory getEarningCategory() {
		return this.earningCategory;
	}

	public void setEarningCategory(EarningCategory earningCategory) {
		this.earningCategory = earningCategory;
	}

	@Column(name = "earning_name", length = 45)
	public String getEarningName() {
		return this.earningName;
	}

	public void setEarningName(String earningName) {
		this.earningName = earningName;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "earning")
	public Set<CompanyEarning> getCompanyEarnings() {
		return this.companyEarnings;
	}

	public void setCompanyEarnings(Set<CompanyEarning> companyEarnings) {
		this.companyEarnings = companyEarnings;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Earning [id=");
		builder.append(id);
		builder.append(", earningCategory=");
		builder.append(earningCategory.getId());
		builder.append(", earningName=");
		builder.append(earningName);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
