package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeDepartmentAllocation generated by hbm2java
 */
@Entity
@Table(name = "employee_department_allocation")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class EmployeeDepartmentAllocation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7217831701021356812L;
	private Long id;
	private Employee employee;
	private CompanyDepartment companyDepartment;
	private BigDecimal allocationPerentage;

	public EmployeeDepartmentAllocation() {
	}

	public EmployeeDepartmentAllocation(Employee employee, CompanyDepartment companyDepartment) {
		this.employee = employee;
		this.companyDepartment = companyDepartment;
	}

	public EmployeeDepartmentAllocation(Employee employee, CompanyDepartment companyDepartment,
			BigDecimal allocationPerentage) {
		this.employee = employee;
		this.companyDepartment = companyDepartment;
		this.allocationPerentage = allocationPerentage;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_id")
	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_department_id")
	public CompanyDepartment getCompanyDepartment() {
		return this.companyDepartment;
	}

	public void setCompanyDepartment(CompanyDepartment companyDepartment) {
		this.companyDepartment = companyDepartment;
	}

	@Column(name = "allocation_perentage", precision = 3, scale = 2)
	public BigDecimal getAllocationPerentage() {
		return this.allocationPerentage;
	}

	public void setAllocationPerentage(BigDecimal allocationPerentage) {
		this.allocationPerentage = allocationPerentage;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("EmployeeDepartmentAllocation [id=");
		builder.append(id);
		builder.append(", employee=");
		builder.append(employee.getId());
		builder.append(", companyDepartment=");
		builder.append(companyDepartment.getId());
		builder.append(", allocationPerentage=");
		builder.append(allocationPerentage);
		builder.append("]");
		return builder.toString();
	}

}
