package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * EmployeeAllowanceRecord generated by hbm2java
 */
@Entity
@Table(name = "employee_allowance_record")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class EmployeeAllowanceRecord implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6434127757940808004L;
	private Long id;
	private EmployeeW4Detail employeeW4Detail;
	private AllowanceType allowanceType;
	private Long noOfAllowance;
	private Date asOnDate;

	public EmployeeAllowanceRecord() {
	}

	public EmployeeAllowanceRecord(EmployeeW4Detail employeeW4Detail, AllowanceType allowanceType,
			Long noOfAllowance, Date asOnDate) {
		this.employeeW4Detail = employeeW4Detail;
		this.allowanceType = allowanceType;
		this.noOfAllowance = noOfAllowance;
		this.asOnDate = asOnDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "employee_w4_detail_id")
	public EmployeeW4Detail getEmployeeW4Detail() {
		return this.employeeW4Detail;
	}

	public void setEmployeeW4Detail(EmployeeW4Detail employeeW4Detail) {
		this.employeeW4Detail = employeeW4Detail;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "allowance_type_id")
	public AllowanceType getAllowanceType() {
		return this.allowanceType;
	}

	public void setAllowanceType(AllowanceType allowanceType) {
		this.allowanceType = allowanceType;
	}

	@Column(name = "no_of_allowance")
	public Long getNoOfAllowance() {
		return this.noOfAllowance;
	}

	public void setNoOfAllowance(Long noOfAllowance) {
		this.noOfAllowance = noOfAllowance;
	}

	// @Temporal(TemporalType.TIMESTAMP)
	@Column(name = "as_on_date", columnDefinition = "TIMESTAMP DEFAULT CURRENT_TIMESTAMP")
	public Date getAsOnDate() {
		return this.asOnDate;
	}

	public void setAsOnDate(Date asOnDate) {
		this.asOnDate = asOnDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("EmployeeAllowanceRecord [id=");
		builder.append(id);
		builder.append(", employeeW4Detail=");
		builder.append(employeeW4Detail.getId());
		builder.append(", allowanceType=");
		builder.append(allowanceType.getId());
		builder.append(", noOfAllowance=");
		builder.append(noOfAllowance);
		builder.append(", asOnDate=");
		builder.append(asOnDate);
		builder.append("]");
		return builder.toString();
	}

}
