package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CompanyCalendar generated by hbm2java
 */
@Entity
@Table(name = "federal_state_holiday")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class FederalStateHoliday implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4281309684983826901L;
	private Long id;
	private UsState usState;
	private Date holidayDate;
	private String holidayDescription;

	public FederalStateHoliday() {
	}

	public FederalStateHoliday(UsState usState, Date holidayDate) {
		this.usState = usState;
		this.holidayDate = holidayDate;
	}

	public FederalStateHoliday(UsState usState, Date holidayDate, String holidayDescription) {
		this.usState = usState;
		this.holidayDate = holidayDate;
		this.holidayDescription = holidayDescription;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "state_id")
	public UsState getUsState() {
		return usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "holiday_date", length = 10)
	public Date getHolidayDate() {
		return this.holidayDate;
	}

	public void setHolidayDate(Date holidayDate) {
		this.holidayDate = holidayDate;
	}

	@Column(name = "holiday_description", length = 300)
	public String getHolidayDescription() {
		return this.holidayDescription;
	}

	public void setHolidayDescription(String holidayDescription) {
		this.holidayDescription = holidayDescription;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FederalStateHoliday [id=");
		builder.append(id);
		builder.append(", usState=");
		builder.append(usState.getId());
		builder.append(", holidayDate=");
		builder.append(holidayDate);
		builder.append(", holidayDescription=");
		builder.append(holidayDescription);
		builder.append("]");
		return builder.toString();
	}

}
