package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FundCategory generated by hbm2java
 */
@Entity
@Table(name = "fund_category")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class FundCategory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6695067483923509147L;
	private Long id;
	private String categoryName;
	private String description;
	private Set<FundTransaction> fundTransactions = new HashSet<FundTransaction>(0);

	public FundCategory() {
	}

	public FundCategory(String categoryName, String description,
			Set<FundTransaction> fundTransactions) {
		this.categoryName = categoryName;
		this.description = description;
		this.fundTransactions = fundTransactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "category_name", length = 45, unique = true)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fundCategory")
	public Set<FundTransaction> getCompanyTransactions() {
		return this.fundTransactions;
	}

	public void setCompanyTransactions(Set<FundTransaction> fundTransactions) {
		this.fundTransactions = fundTransactions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FundCategory [id=");
		builder.append(id);
		builder.append(", categoryName=");
		builder.append(categoryName);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
