package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SutaTaxRate generated by hbm2java
 */
@Entity
@Table(name = "futa_suta_tax_rate")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class FutaSutaTaxRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4409580028322191498L;
	private Long id;
	private TaxType taxType;
	private Company company;
	private BigDecimal rate;
	private Date dateOfEntry;
	private Date wef;
	private Date releaseDate;

	public FutaSutaTaxRate() {
	}

	public FutaSutaTaxRate(TaxType taxType, Company company) {
		this.taxType = taxType;
		this.company = company;
	}

	public FutaSutaTaxRate(TaxType taxType, Company company, BigDecimal rate, Date dateOfEntry,
			Date wef, Date releaseDate) {
		this.taxType = taxType;
		this.company = company;
		this.rate = rate;
		this.dateOfEntry = dateOfEntry;
		this.wef = wef;
		this.releaseDate = releaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_type_id")
	public TaxType getTaxType() {
		return this.taxType;
	}

	public void setTaxType(TaxType taxType) {
		this.taxType = taxType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@Column(name = "rate", precision = 10, scale = 2)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("FutaSutaTaxRate [id=");
		builder.append(id);
		builder.append(", taxType=");
		builder.append(taxType.getId());
		builder.append(", company=");
		builder.append(company.getId());
		builder.append(", rate=");
		builder.append(rate);
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", wef=");
		builder.append(wef);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append("]");
		return builder.toString();
	}

}
