package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PaymentMode generated by hbm2java
 */
@Entity
@Table(name = "payment_mode")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class PaymentMode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8409446290137535596L;
	private long id;
	private String mode;
	private String description;
	private Set<FundTransaction> fundTransactions = new HashSet<FundTransaction>(0);

	public PaymentMode() {
	}

	public PaymentMode(long id, String mode) {
		this.id = id;
		this.mode = mode;
	}

	public PaymentMode(long id, String mode, String description,
			Set<FundTransaction> fundTransactions) {
		this.id = id;
		this.mode = mode;
		this.description = description;
		this.fundTransactions = fundTransactions;
	}

	@Id
	@Column(name = "id", unique = true)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "mode", length = 45, unique = true)
	public String getMode() {
		return this.mode;
	}

	public void setMode(String mode) {
		this.mode = mode;
	}

	@Column(name = "description", length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "paymentMode")
	public Set<FundTransaction> getCompanyTransactions() {
		return this.fundTransactions;
	}

	public void setCompanyTransactions(Set<FundTransaction> fundTransactions) {
		this.fundTransactions = fundTransactions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PaymentMode [id=");
		builder.append(id);
		builder.append(", mode=");
		builder.append(mode);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
