package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PayrollTaxContribution generated by hbm2java
 */
@Entity
@Table(name = "payroll_tax_contribution")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class PayrollTaxContribution implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3970679924343882911L;
	private Long id;
	private Payroll payroll;
	private TaxType taxType;
	private BigDecimal employeeContri;
	private BigDecimal companyContri;

	public PayrollTaxContribution() {
	}

	public PayrollTaxContribution(Payroll payroll, TaxType taxType) {
		this.payroll = payroll;
		this.taxType = taxType;
	}

	public PayrollTaxContribution(Payroll payroll, TaxType taxType, BigDecimal employeeContri,
			BigDecimal companyContri) {
		this.payroll = payroll;
		this.taxType = taxType;
		this.employeeContri = employeeContri;
		this.companyContri = companyContri;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payroll_id")
	public Payroll getPayroll() {
		return this.payroll;
	}

	public void setPayroll(Payroll payroll) {
		this.payroll = payroll;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_type_id")
	public TaxType getTaxType() {
		return this.taxType;
	}

	public void setTaxType(TaxType taxType) {
		this.taxType = taxType;
	}

	@Column(name = "employee_contri", precision = 10, scale = 2)
	public BigDecimal getEmployeeContri() {
		return this.employeeContri;
	}

	public void setEmployeeContri(BigDecimal employeeContri) {
		this.employeeContri = employeeContri;
	}

	@Column(name = "company_contri", precision = 10, scale = 2)
	public BigDecimal getCompanyContri() {
		return this.companyContri;
	}

	public void setCompanyContri(BigDecimal companyContri) {
		this.companyContri = companyContri;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PayrollTaxContribution [id=");
		builder.append(id);
		builder.append(", payroll=");
		builder.append(payroll.getId());
		builder.append(", taxType=");
		builder.append(taxType.getId());
		builder.append(", employeeContri=");
		builder.append(employeeContri);
		builder.append(", companyContri=");
		builder.append(companyContri);
		builder.append("]");
		return builder.toString();
	}

}
