package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Person generated by hbm2java
 */
@Entity
@Table(name = "person")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Person implements java.io.Serializable {

	private static final long serialVersionUID = 3034902967508063455L;
	private Long id;
	private ContactType contactType;
	private String firstName;
	private String middleName;
	private String lastName;
	private Date dob;
	private String ssn;
	private String phone;
	private String mobile;
	private String ext;
	private String email;
	private String gender;
	private String fax;
	private String designation;
	private Set<PayrollCompany> payrollCompanies = new HashSet<PayrollCompany>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Message> messages = new HashSet<Message>(0);
	private Set<ToMessageMap> toMessageMaps = new HashSet<ToMessageMap>(0);

	public Person() {
	}

	public Person(String person) {
		this.firstName = person;
	}

	public Person(ContactType contactType) {
		this.contactType = contactType;
	}

	public Person(Long id, String firstName, String lastName, String email) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.email = email;
	}

	public Person(ContactType contactType, String designation, Date dob, String email,
			String gender, String ext, String fax, String firstName, String lastName,
			String middleName, String mobile, String phone, String ssn,
			Set<PayrollCompany> payrollCompanies, Set<User> users, Set<Employee> employees,
			Set<Message> messages, Set<ToMessageMap> toMessageMaps) {
		this.contactType = contactType;
		this.designation = designation;
		this.dob = dob;
		this.email = email;
		this.gender = gender;
		this.ext = ext;
		this.fax = fax;
		this.firstName = firstName;
		this.lastName = lastName;
		this.middleName = middleName;
		this.mobile = mobile;
		this.phone = phone;
		this.ssn = ssn;
		this.payrollCompanies = payrollCompanies;
		this.users = users;
		this.employees = employees;
		this.messages = messages;
		this.toMessageMaps = toMessageMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "contact_type_id")
	public ContactType getContactType() {
		return this.contactType;
	}

	public void setContactType(ContactType contactType) {
		this.contactType = contactType;
	}

	@Column(name = "first_name", length = 30)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 30)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 30)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dob", length = 10)
	public Date getDob() {
		return this.dob;
	}

	public void setDob(Date dob) {
		this.dob = dob;
	}

	@Column(name = "ssn", length = 9)
	public String getSsn() {
		return this.ssn;
	}

	public void setSsn(String ssn) {
		this.ssn = ssn;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "mobile", length = 15)
	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	@Column(name = "ext", length = 10)
	public String getExt() {
		return this.ext;
	}

	public void setExt(String ext) {
		this.ext = ext;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "gender", length = 45)
	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "designation", length = 45)
	public String getDesignation() {
		return this.designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<PayrollCompany> getPayrollCompanies() {
		return this.payrollCompanies;
	}

	public void setPayrollCompanies(Set<PayrollCompany> payrollCompanies) {
		this.payrollCompanies = payrollCompanies;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person", cascade = CascadeType.ALL)
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "person")
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "fromPerson")
	public Set<Message> getMessages() {
		return messages;
	}

	public void setMessages(Set<Message> messages) {
		this.messages = messages;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "toPerson")
	public Set<ToMessageMap> getToMessageMaps() {
		return toMessageMaps;
	}

	public void setToMessageMaps(Set<ToMessageMap> toMessageMaps) {
		this.toMessageMaps = toMessageMaps;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Person [id=");
		builder.append(id);
		builder.append(", firstName=");
		builder.append(firstName);
		builder.append(", middleName=");
		builder.append(middleName);
		builder.append(", lastName=");
		builder.append(lastName);
		builder.append(", dob=");
		builder.append(dob);
		builder.append(", ssn=");
		builder.append(ssn);
		builder.append(", phone=");
		builder.append(phone);
		builder.append(", mobile=");
		builder.append(mobile);
		builder.append(", ext=");
		builder.append(ext);
		builder.append(", email=");
		builder.append(email);
		builder.append(", gender=");
		builder.append(gender);
		builder.append(", fax=");
		builder.append(fax);
		builder.append(", designation=");
		builder.append(designation);
		builder.append("]");
		return builder.toString();
	}

}
