package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PlanService generated by hbm2java
 */
@Entity
@Table(name = "plan_feature")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class PlanFeature implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1998738971681142676L;
	private Long id;
	private PayrollPlan payrollPlan;
	private String service;
	private String description;
	private Set<CompanyFeature> companyFeatures = new HashSet<CompanyFeature>(0);

	public PlanFeature() {
	}

	public PlanFeature(PayrollPlan payrollPlan, String service) {
		this.payrollPlan = payrollPlan;
		this.service = service;
	}

	public PlanFeature(PayrollPlan payrollPlan, String service, String description,
			Set<CompanyFeature> companyFeatures) {
		this.payrollPlan = payrollPlan;
		this.service = service;
		this.description = description;
		this.companyFeatures = companyFeatures;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "payroll_plan_id")
	public PayrollPlan getPayrollPlan() {
		return this.payrollPlan;
	}

	public void setPayrollPlan(PayrollPlan payrollPlan) {
		this.payrollPlan = payrollPlan;
	}

	@Column(name = "service", length = 45, unique = true)
	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planFeature")
	public Set<CompanyFeature> getCompanyFeatures() {
		return this.companyFeatures;
	}

	public void setCompanyFeatures(Set<CompanyFeature> companyFeatures) {
		this.companyFeatures = companyFeatures;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PlanService [id=");
		builder.append(id);
		builder.append(", productPlan=");
		builder.append(payrollPlan.getId());
		builder.append(", service=");
		builder.append(service);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
