package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import com.epayroll.constant.Section;
import com.epayroll.entity.Role.RoleType;

/**
 * SectionRolePermissionMap generated by hbm2java
 */
@Entity
@Table(name = "role_type_section_map")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class RoleTypeSectionMap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4959261438939188031L;
	private Long id;
	private Section section;
	private RoleType roleType;

	public RoleTypeSectionMap() {
	}

	public RoleTypeSectionMap(Section section, RoleType roleType) {
		this.section = section;
		this.roleType = roleType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "section")
	public Section getSection() {
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "role_type")
	public RoleType getRoleType() {
		return roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("RoleTypeSectionMap [id=");
		builder.append(id);
		builder.append(", section=");
		builder.append(section);
		builder.append(", roleType=");
		builder.append(roleType);
		builder.append("]");
		return builder.toString();
	}

}
