package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class Role implements java.io.Serializable {

	private static final long serialVersionUID = -4279547562476315322L;

	public enum RoleType {
		SYSTEM_SUPER_USER("System Super User"), SYSTEM_USER("System User"), COMPANY_SUPER_USER(
				"Company Super User"), COMPANY_USER("Company User");
		private String name;

		private RoleType(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	private Long id;
	private String roleName;
	private RoleType roleType;
	private String roleDescription;
	private Set<User> users = new HashSet<User>(0);
	private Set<SectionRolePermissionMap> sectionRolePermissionMaps = new HashSet<SectionRolePermissionMap>(
			0);

	public Role() {
	}

	public Role(String roleName, RoleType roleType) {
		this.roleName = roleName;
		this.setRoleType(roleType);
	}

	public Role(String roleName, RoleType roleType, String roleDescription, Set<User> users,
			Set<SectionRolePermissionMap> sectionRolePermissionMaps) {
		this.roleName = roleName;
		this.setRoleType(roleType);
		this.roleDescription = roleDescription;
		this.users = users;
		this.sectionRolePermissionMaps = sectionRolePermissionMaps;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "role_name", length = 45)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_type")
	public RoleType getRoleType() {
		return roleType;
	}

	public void setRoleType(RoleType roleType) {
		this.roleType = roleType;
	}

	@Column(name = "role_description", length = 300)
	public String getRoleDescription() {
		return this.roleDescription;
	}

	public void setRoleDescription(String roleDescription) {
		this.roleDescription = roleDescription;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<SectionRolePermissionMap> getSectionRolePermissionMaps() {
		return this.sectionRolePermissionMaps;
	}

	public void setSectionRolePermissionMaps(Set<SectionRolePermissionMap> sectionRolePermissionMaps) {
		this.sectionRolePermissionMaps = sectionRolePermissionMaps;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Role [id=");
		builder.append(id);
		builder.append(", roleName=");
		builder.append(roleName);
		builder.append(", roleType=");
		builder.append(roleType);
		builder.append(", roleDescription=");
		builder.append(roleDescription);
		builder.append("]");
		return builder.toString();
	}

}
