package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.epayroll.constant.PermissionType;
import com.epayroll.constant.Section;

/**
 * SectionRolePermissionMap generated by hbm2java
 */
@Entity
@Table(name = "section_role_permission_map")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class SectionRolePermissionMap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4959261438939188031L;
	private Long id;
	private Company company;
	private Role role;
	private Section section;
	private PermissionType permissionType;

	public SectionRolePermissionMap() {
	}

	public SectionRolePermissionMap(Company company, Section section, Role role,
			PermissionType permissionType) {
		this.company = company;
		this.section = section;
		this.role = role;
		this.permissionType = permissionType;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_id")
	public Company getCompany() {
		return this.company;
	}

	public void setCompany(Company company) {
		this.company = company;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "section")
	public Section getSection() {
		return section;
	}

	public void setSection(Section section) {
		this.section = section;
	}

	@Column(name = "permission_type")
	public PermissionType getPermissionType() {
		return permissionType;
	}

	public void setPermissionType(PermissionType permissionType) {
		this.permissionType = permissionType;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SectionRolePermissionMap [id=");
		builder.append(id);
		builder.append(", company=");
		builder.append(company);
		builder.append(", role=");
		builder.append(role.getId());
		builder.append(", section=");
		builder.append(section);
		builder.append(", permissionType=");
		builder.append(permissionType);
		builder.append("]");
		return builder.toString();
	}

}
