package com.epayroll.entity;

// Generated Dec 22, 2012 3:36:44 AM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * StandardDeductionRate generated by hbm2java
 */
@Entity
@Table(name = "standard_deduction_rate")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class StandardDeductionRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8095721568531480590L;
	private Long id;
	private UsState usState;
	private FilingStatus filingStatus;
	private BigDecimal minValue;
	private BigDecimal maxValue;
	private BigDecimal rate;
	private RateValueType rateValueType;
	private Date dateOfEntry;
	private Date wef;
	private Date releaseDate;

	public enum RateValueType {
		PERCENTAGE("Percentage"), AMOUNT("Amount");
		private String name;

		private RateValueType(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public StandardDeductionRate() {
	}

	public StandardDeductionRate(UsState usState, FilingStatus filingStatus) {
		this.usState = usState;
		this.filingStatus = filingStatus;
	}

	public StandardDeductionRate(UsState usState, FilingStatus filingStatus, BigDecimal minValue,
			BigDecimal maxValue, BigDecimal rate, RateValueType rateValueType, Date dateOfEntry,
			Date wef, Date releaseDate) {
		this.usState = usState;
		this.filingStatus = filingStatus;
		this.minValue = minValue;
		this.maxValue = maxValue;
		this.rate = rate;
		this.rateValueType = rateValueType;
		this.dateOfEntry = dateOfEntry;
		this.wef = wef;
		this.releaseDate = releaseDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_state_id")
	public UsState getUsState() {
		return this.usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "filing_status_id")
	public FilingStatus getFilingStatus() {
		return this.filingStatus;
	}

	public void setFilingStatus(FilingStatus filingStatus) {
		this.filingStatus = filingStatus;
	}

	@Column(name = "min_value", precision = 10, scale = 2)
	public BigDecimal getMinValue() {
		return this.minValue;
	}

	public void setMinValue(BigDecimal minValue) {
		this.minValue = minValue;
	}

	@Column(name = "max_value", precision = 10, scale = 2)
	public BigDecimal getMaxValue() {
		return this.maxValue;
	}

	public void setMaxValue(BigDecimal maxValue) {
		this.maxValue = maxValue;
	}

	@Column(name = "rate", precision = 10, scale = 2)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Column(name = "rate_value_type", precision = 10, scale = 2)
	public RateValueType getRateValueType() {
		return this.rateValueType;
	}

	public void setRateValueType(RateValueType rateValueType) {
		this.rateValueType = rateValueType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("StandardDeductionRate [id=");
		builder.append(id);
		builder.append(", usState=");
		builder.append(usState);
		builder.append(", filingStatus=");
		builder.append(filingStatus.getId());
		builder.append(", minValue=");
		builder.append(minValue);
		builder.append(", maxValue=");
		builder.append(maxValue);
		builder.append(", rate=");
		builder.append(rate);
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", rateValueType=");
		builder.append(rateValueType);
		builder.append(", wef=");
		builder.append(wef);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append("]");
		return builder.toString();
	}

}
