package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SectionRolePermissionMap generated by hbm2java
 */
@Entity
@Table(name = "system_message_user_map")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class SystemMessageUserMap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4959261438939188031L;
	private Long id;
	private User user;
	private SystemMessage systemMessage;
	private Status status;

	public enum Status {
		ACTIVE("Active"), INACTIVE("InActive");
		private String name;

		private Status(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public SystemMessageUserMap() {
	}

	public SystemMessageUserMap(User user, SystemMessage systemMessage, Status status) {
		this.user = user;
		this.setSystemMessage(systemMessage);
		this.setStatus(status);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "system_message_id")
	public SystemMessage getSystemMessage() {
		return systemMessage;
	}

	public void setSystemMessage(SystemMessage systemMessage) {
		this.systemMessage = systemMessage;
	}

	@Column(name = "status")
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SystemMessageUserMap [id=");
		builder.append(id);
		builder.append(", user=");
		builder.append(user.getId());
		builder.append(", systemMessage=");
		builder.append(systemMessage.getId());
		builder.append(", status=");
		builder.append(status);
		builder.append("]");
		return builder.toString();
	}

}
