package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SectionRolePermissionMap generated by hbm2java
 */
@Entity
@Table(name = "system_task_user_map")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class SystemTaskUserMap implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4959261438939188031L;
	private Long id;
	private User user;
	private SystemTask systemTask;
	private Status status;

	public enum Status {
		ACTIVE("Active"), INACTIVE("InActive"), COMPLETE("Complete"), INCOMPLETE("Incomplete");
		private String name;

		private Status(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public SystemTaskUserMap() {
	}

	public SystemTaskUserMap(User user, SystemTask systemTask, Status status) {
		this.user = user;
		this.systemTask = systemTask;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "system_task_id")
	public SystemTask getSystemTask() {
		return systemTask;
	}

	public void setSystemTask(SystemTask systemTask) {
		this.systemTask = systemTask;
	}

	@Column(name = "status")
	public Status getStatus() {
		return status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("SystemTaskUserMap [id=");
		builder.append(id);
		builder.append(", user=");
		builder.append(user.getId());
		builder.append(", systemTask=");
		builder.append(systemTask.getId());
		builder.append(", status=");
		builder.append(status);
		builder.append("]");
		return builder.toString();
	}

}
