package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * TaxAuthority generated by hbm2java
 */
@Entity
@Table(name = "tax_authority")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class TaxAuthority implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -767741260098683326L;
	private Long id;
	private UsState usState;
	private UsCounty usCounty;
	private Address address;
	private String authorityName;
	private String emailId;
	private String webAddress;
	private String phone;
	private String fax;
	private String description;
	private Set<TaxType> taxTypes = new HashSet<TaxType>(0);
	private Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles = new HashSet<TaxAuthorityDepositCycle>(
			0);

	public TaxAuthority() {
	}

	public TaxAuthority(UsState usState, UsCounty usCounty, String authorityName) {
		this.usState = usState;
		this.setUsCounty(usCounty);
		this.authorityName = authorityName;
	}

	public TaxAuthority(UsState usState, UsCounty usCounty, Address address, String authorityName,
			String description, String emailId, String fax, String phone, String webAddress,
			Set<TaxType> taxTypes, Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles) {
		this.usState = usState;
		this.setUsCounty(usCounty);
		this.address = address;
		this.authorityName = authorityName;
		this.description = description;
		this.emailId = emailId;
		this.fax = fax;
		this.phone = phone;
		this.webAddress = webAddress;
		this.taxTypes = taxTypes;
		this.setTaxAuthorityDepositCycles(taxAuthorityDepositCycles);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_state_id", nullable = true)
	public UsState getUsState() {
		return this.usState;
	}

	public void setUsState(UsState usState) {
		this.usState = usState;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "us_county_id", nullable = true)
	public UsCounty getUsCounty() {
		return usCounty;
	}

	public void setUsCounty(UsCounty usCounty) {
		this.usCounty = usCounty;
	}

	@ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	@JoinColumn(name = "address_id")
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "authority_name", length = 45, unique = true)
	public String getAuthorityName() {
		return this.authorityName;
	}

	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName;
	}

	@Column(name = "email_id", length = 30)
	public String getEmailId() {
		return this.emailId;
	}

	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}

	@Column(name = "web_address", length = 20)
	public String getWebAddress() {
		return this.webAddress;
	}

	public void setWebAddress(String webAddress) {
		this.webAddress = webAddress;
	}

	@Column(name = "phone", length = 15)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax", length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxAuthority")
	public Set<TaxType> getTaxTypes() {
		return this.taxTypes;
	}

	public void setTaxTypes(Set<TaxType> taxTypes) {
		this.taxTypes = taxTypes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxAuthority")
	public Set<TaxAuthorityDepositCycle> getTaxAuthorityDepositCycles() {
		return taxAuthorityDepositCycles;
	}

	public void setTaxAuthorityDepositCycles(Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles) {
		this.taxAuthorityDepositCycles = taxAuthorityDepositCycles;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TaxAuthority [id=");
		builder.append(id);
		builder.append(", usState=");
		builder.append(usState);
		builder.append(", usCounty=");
		builder.append(usCounty);
		builder.append(", address=");
		builder.append(address);
		builder.append(", authorityName=");
		builder.append(authorityName);
		builder.append(", emailId=");
		builder.append(emailId);
		builder.append(", webAddress=");
		builder.append(webAddress);
		builder.append(", phone=");
		builder.append(phone);
		builder.append(", fax=");
		builder.append(fax);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
