package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TaxAuthority generated by hbm2java
 */
@Entity
@Table(name = "tax_authority_deposit_cycle")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class TaxAuthorityDepositCycle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -767741260098683326L;
	private Long id;
	private TaxDepositCycle taxDepositCycle;
	private TaxAuthority taxAuthority;
	private BigDecimal minTaxAmount;
	private BigDecimal maxTaxAmount;

	public TaxAuthorityDepositCycle() {
	}

	public TaxAuthorityDepositCycle(TaxDepositCycle taxDepositCycle, TaxAuthority taxAuthority) {
		this.taxDepositCycle = taxDepositCycle;
		this.taxAuthority = taxAuthority;

	}

	public TaxAuthorityDepositCycle(TaxDepositCycle taxDepositCycle, TaxAuthority taxAuthority,
			BigDecimal minTaxAmount, BigDecimal maxTaxAmount) {
		this.taxDepositCycle = taxDepositCycle;
		this.taxAuthority = taxAuthority;
		this.minTaxAmount = minTaxAmount;
		this.maxTaxAmount = maxTaxAmount;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_deposit_cycle_id")
	public TaxDepositCycle getTaxDepositCycle() {
		return taxDepositCycle;
	}

	public void setTaxDepositCycle(TaxDepositCycle taxDepositCycle) {
		this.taxDepositCycle = taxDepositCycle;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_authority_id")
	public TaxAuthority getTaxAuthority() {
		return taxAuthority;
	}

	public void setTaxAuthority(TaxAuthority taxAuthority) {
		this.taxAuthority = taxAuthority;
	}

	@Column(name = "min_tax_amount", precision = 10, scale = 2)
	public BigDecimal getMinTaxAmount() {
		return minTaxAmount;
	}

	public void setMinTaxAmount(BigDecimal minTaxAmount) {
		this.minTaxAmount = minTaxAmount;
	}

	@Column(name = "max_tax_amount", precision = 10, scale = 2)
	public BigDecimal getMaxTaxAmount() {
		return maxTaxAmount;
	}

	public void setMaxTaxAmount(BigDecimal maxTaxAmount) {
		this.maxTaxAmount = maxTaxAmount;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TaxAuthorityDepositCycle [id=");
		builder.append(id);
		builder.append(", taxDepositCycle=");
		builder.append(taxDepositCycle.getId());
		builder.append(", taxAuthority=");
		builder.append(taxAuthority.getId());
		builder.append(", minTaxAmount=");
		builder.append(minTaxAmount);
		builder.append(", maxTaxAmount=");
		builder.append(maxTaxAmount);
		builder.append("]");
		return builder.toString();
	}

}
