package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * DepositCycle generated by hbm2java
 */
@Entity
@Table(name = "tax_deposit_cycle")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class TaxDepositCycle implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9046652692453565715L;
	private Long id;
	private String cycle;
	private Integer noOfDays;
	private String description;
	private Set<CompanyTax> companyTaxes = new HashSet<CompanyTax>(0);
	private Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles = new HashSet<TaxAuthorityDepositCycle>(
			0);

	public TaxDepositCycle() {
	}

	public TaxDepositCycle(String cycle) {
		this.cycle = cycle;
	}

	public TaxDepositCycle(String cycle, Integer noOfDays, String description,
			Set<CompanyTax> companyTaxes, Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles) {
		this.cycle = cycle;
		this.noOfDays = noOfDays;
		this.description = description;
		this.companyTaxes = companyTaxes;
		this.setTaxAuthorityDepositCycles(taxAuthorityDepositCycles);
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "cycle", length = 45, unique = true)
	public String getCycle() {
		return this.cycle;
	}

	public void setCycle(String cycle) {
		this.cycle = cycle;
	}

	@Column(name = "no_of_days")
	public Integer getNoOfDays() {
		return noOfDays;
	}

	public void setNoOfDays(Integer noOfDays) {
		this.noOfDays = noOfDays;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxDepositCycle")
	public Set<CompanyTax> getCompanyTaxes() {
		return this.companyTaxes;
	}

	public void setCompanyTaxes(Set<CompanyTax> companyTaxes) {
		this.companyTaxes = companyTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxDepositCycle")
	public Set<TaxAuthorityDepositCycle> getTaxAuthorityDepositCycles() {
		return taxAuthorityDepositCycles;
	}

	public void setTaxAuthorityDepositCycles(Set<TaxAuthorityDepositCycle> taxAuthorityDepositCycles) {
		this.taxAuthorityDepositCycles = taxAuthorityDepositCycles;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("DepositCycle [id=");
		builder.append(id);
		builder.append(", cycle=");
		builder.append(cycle);
		builder.append(", noOfDays=");
		builder.append(noOfDays);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
