package com.epayroll.entity;

// Generated Dec 12, 2012 9:09:02 PM by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TaxType generated by hbm2java
 */
@Entity
@Table(name = "tax_type")
@org.hibernate.annotations.Entity(dynamicInsert = true, dynamicUpdate = true)
public class TaxType implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6083024899753098262L;
	private Long id;
	private TaxAuthority taxAuthority;
	private String taxName;
	private Boolean paidByEmployee;
	private Boolean paidByCompany;
	private String description;
	private Set<FutaSutaTaxRate> futaSutaTaxRates = new HashSet<FutaSutaTaxRate>(0);
	private Set<CountyTaxRate> countyTaxRates = new HashSet<CountyTaxRate>(0);
	private Set<CompanyTax> companyTaxes = new HashSet<CompanyTax>(0);
	private Set<EmployeeTax> employeeTaxes = new HashSet<EmployeeTax>(0);
	private Set<FederalStateTaxRate> federalStateTaxRates = new HashSet<FederalStateTaxRate>(0);
	private Set<PayrollTaxContribution> payrollTaxContributions = new HashSet<PayrollTaxContribution>(
			0);

	public TaxType() {
	}

	public enum TaxPayee {
		EMPLOYEE("Employee"), EMPLOYER("Employer");
		private String name;

		private TaxPayee(String name) {
			this.name = name;
		}

		public String getName() {
			return name;
		}
	}

	public TaxType(TaxAuthority taxAuthority, String taxName) {
		this.taxAuthority = taxAuthority;
		this.taxName = taxName;
	}

	public TaxType(TaxAuthority taxAuthority, String description, String taxName,
			Boolean paidByEmployee, Boolean paidByCompany, Set<FutaSutaTaxRate> futaSutaTaxRates,
			Set<CountyTaxRate> countyTaxRates, Set<CompanyTax> companyTaxes,
			Set<EmployeeTax> employeeTaxes, Set<FederalStateTaxRate> federalStateTaxRates) {
		this.taxAuthority = taxAuthority;
		this.description = description;
		this.taxName = taxName;
		this.paidByEmployee = paidByEmployee;
		this.paidByCompany = paidByCompany;
		this.futaSutaTaxRates = futaSutaTaxRates;
		this.countyTaxRates = countyTaxRates;
		this.companyTaxes = companyTaxes;
		this.employeeTaxes = employeeTaxes;
		this.federalStateTaxRates = federalStateTaxRates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tax_authority_id")
	public TaxAuthority getTaxAuthority() {
		return this.taxAuthority;
	}

	public void setTaxAuthority(TaxAuthority taxAuthority) {
		this.taxAuthority = taxAuthority;
	}

	@Column(name = "tax_name", length = 45, unique = true)
	public String getTaxName() {
		return this.taxName;
	}

	public void setTaxName(String taxName) {
		this.taxName = taxName;
	}

	@Column(name = "paid_by_employee")
	public Boolean getPaidByEmployee() {
		return paidByEmployee;
	}

	public void setPaidByEmployee(Boolean paidByEmployee) {
		this.paidByEmployee = paidByEmployee;
	}

	@Column(name = "paid_by_company")
	public Boolean getPaidByCompany() {
		return paidByCompany;
	}

	public void setPaidByCompany(Boolean paidByCompany) {
		this.paidByCompany = paidByCompany;
	}

	@Column(name = "description", length = 300)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType")
	public Set<FutaSutaTaxRate> getFutaSutaTaxRates() {
		return this.futaSutaTaxRates;
	}

	public void setFutaSutaTaxRates(Set<FutaSutaTaxRate> futaSutaTaxRates) {
		this.futaSutaTaxRates = futaSutaTaxRates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType")
	public Set<CountyTaxRate> getCountyTaxRates() {
		return this.countyTaxRates;
	}

	public void setCountyTaxRates(Set<CountyTaxRate> countyTaxRates) {
		this.countyTaxRates = countyTaxRates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType")
	public Set<CompanyTax> getCompanyTaxes() {
		return this.companyTaxes;
	}

	public void setCompanyTaxes(Set<CompanyTax> companyTaxes) {
		this.companyTaxes = companyTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType", cascade = CascadeType.ALL)
	public Set<EmployeeTax> getEmployeeTaxes() {
		return this.employeeTaxes;
	}

	public void setEmployeeTaxes(Set<EmployeeTax> employeeTaxes) {
		this.employeeTaxes = employeeTaxes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType")
	public Set<PayrollTaxContribution> getPayrollTaxContributions() {
		return this.payrollTaxContributions;
	}

	public void setPayrollTaxContributions(Set<PayrollTaxContribution> payrollTaxContributions) {
		this.payrollTaxContributions = payrollTaxContributions;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "taxType")
	public Set<FederalStateTaxRate> getFederalStateTaxRates() {
		return this.federalStateTaxRates;
	}

	public void setFederalStateTaxRates(Set<FederalStateTaxRate> federalStateTaxRates) {
		this.federalStateTaxRates = federalStateTaxRates;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("TaxType [id=");
		builder.append(id);
		builder.append(", taxAuthority=");
		builder.append(taxAuthority.getId());
		builder.append(", taxName=");
		builder.append(taxName);
		builder.append(", paidByEmployee=");
		builder.append(paidByEmployee);
		builder.append(", paidByCompany=");
		builder.append(paidByCompany);
		builder.append(", description=");
		builder.append(description);
		builder.append("]");
		return builder.toString();
	}

}
