package com.epayroll.entity;

// Generated Jan 8, 2013 2:52:22 AM by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * WorkersCompensationTaxRate generated by hbm2java
 */
@Entity
@Table(name = "workers_compensation_tax_rate")
public class WorkersCompensationTaxRate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8982798057770458009L;
	private Long id;
	private CompanyWorkerCompensation companyWorkerCompensation;
	private Date dateOfEntry;
	private BigDecimal rate;
	private Date releaseDate;
	private Date wef;

	public WorkersCompensationTaxRate() {
	}

	public WorkersCompensationTaxRate(CompanyWorkerCompensation companyWorkerCompensation) {
		this.companyWorkerCompensation = companyWorkerCompensation;
	}

	public WorkersCompensationTaxRate(CompanyWorkerCompensation companyWorkerCompensation,
			Date dateOfEntry, BigDecimal rate, Date releaseDate, Date wef) {
		this.companyWorkerCompensation = companyWorkerCompensation;
		this.dateOfEntry = dateOfEntry;
		this.rate = rate;
		this.releaseDate = releaseDate;
		this.wef = wef;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "company_worker_compensation_id")
	public CompanyWorkerCompensation getCompanyWorkerCompensation() {
		return this.companyWorkerCompensation;
	}

	public void setCompanyWorkerCompensation(CompanyWorkerCompensation companyWorkerCompensation) {
		this.companyWorkerCompensation = companyWorkerCompensation;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_entry", length = 19)
	public Date getDateOfEntry() {
		return this.dateOfEntry;
	}

	public void setDateOfEntry(Date dateOfEntry) {
		this.dateOfEntry = dateOfEntry;
	}

	@Column(name = "rate", precision = 10, scale = 2)
	public BigDecimal getRate() {
		return this.rate;
	}

	public void setRate(BigDecimal rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 19)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "wef", length = 19)
	public Date getWef() {
		return this.wef;
	}

	public void setWef(Date wef) {
		this.wef = wef;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("WorkersCompensationTaxRate [id=");
		builder.append(id);
		builder.append(", companyWorkerCompensation=");
		builder.append(companyWorkerCompensation.getId());
		builder.append(", dateOfEntry=");
		builder.append(dateOfEntry);
		builder.append(", rate=");
		builder.append(rate);
		builder.append(", releaseDate=");
		builder.append(releaseDate);
		builder.append(", wef=");
		builder.append(wef);
		builder.append("]");
		return builder.toString();
	}

}
