package com.epayroll.entity;

// Generated Jan 8, 2013 4:53:46 AM by Hibernate Tools 3.6.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * WorkersCompensationTaxRateView generated by hbm2java
 */
@Entity
@Table(name = "workers_compensation_tax_rate_view")
public class WorkersCompensationTaxRateView implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3225445667230538502L;
	private WorkersCompensationTaxRateViewId id;

	public WorkersCompensationTaxRateView() {
	}

	public WorkersCompensationTaxRateView(WorkersCompensationTaxRateViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "code", column = @Column(name = "code", length = 45)),
			@AttributeOverride(name = "description", column = @Column(name = "description")),
			@AttributeOverride(name = "rate", column = @Column(name = "rate", precision = 7, scale = 3)),
			@AttributeOverride(name = "id", column = @Column(name = "id")),
			@AttributeOverride(name = "stateName", column = @Column(name = "state_name", length = 45)) })
	public WorkersCompensationTaxRateViewId getId() {
		return this.id;
	}

	public void setId(WorkersCompensationTaxRateViewId id) {
		this.id = id;
	}

	@Override
	public String toString() {
		return "WorkersCompensationTaxRateView [id=" + id + "]";
	}

}
