//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

package com.epayroll.ws.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for FilingStatusType.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="FilingStatusType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Regular"/>
 *     &lt;enumeration value="Supplemental"/>
 *     &lt;enumeration value="Exempt"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "FilingStatusType")
@XmlEnum
public enum FilingStatusType {

	@XmlEnumValue("Regular")
	REGULAR("Regular"), @XmlEnumValue("Supplemental")
	SUPPLEMENTAL("Supplemental"), @XmlEnumValue("Exempt")
	EXEMPT("Exempt");
	private final String value;

	FilingStatusType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static FilingStatusType fromValue(String v) {
		for (FilingStatusType c : FilingStatusType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
