//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.i-techsoftware.com/vjs-payroll", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.epayroll.ws.pojo;

