//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

package com.epayroll.ws.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for PayFrequencyType.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="PayFrequencyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Daily"/>
 *     &lt;enumeration value="Weekly"/>
 *     &lt;enumeration value="Bi-weekly"/>
 *     &lt;enumeration value="Semi-monthly"/>
 *     &lt;enumeration value="Monthly"/>
 *     &lt;enumeration value="Quaterly"/>
 *     &lt;enumeration value="Semi-annually"/>
 *     &lt;enumeration value="Annually"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "PayFrequencyType")
@XmlEnum
public enum PayFrequencyType {

	@XmlEnumValue("Daily")
	DAILY("Daily"), @XmlEnumValue("Weekly")
	WEEKLY("Weekly"), @XmlEnumValue("Bi-weekly")
	BI_WEEKLY("Bi-weekly"), @XmlEnumValue("Semi-monthly")
	SEMI_MONTHLY("Semi-monthly"), @XmlEnumValue("Monthly")
	MONTHLY("Monthly"), @XmlEnumValue("Quaterly")
	QUATERLY("Quaterly"), @XmlEnumValue("Semi-annually")
	SEMI_ANNUALLY("Semi-annually"), @XmlEnumValue("Annually")
	ANNUALLY("Annually");
	private final String value;

	PayFrequencyType(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static PayFrequencyType fromValue(String v) {
		for (PayFrequencyType c : PayFrequencyType.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
