//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

package com.epayroll.ws.pojo;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MonthlyGrossPay" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="FIT" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="SocialSecurity" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="Medicare" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="SIT" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="Deductions" type="{http://www.i-techsoftware.com/vjs-payroll}DedeuctionType" maxOccurs="10"/>
 *         &lt;element name="NetPay" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "monthlyGrossPay", "fit", "socialSecurity", "medicare", "sit",
		"deductions", "netPay" })
@XmlRootElement(name = "PayrollResponse")
public class PayrollResponse {

	@XmlElement(name = "MonthlyGrossPay", required = true)
	protected BigDecimal monthlyGrossPay;
	@XmlElement(name = "FIT", required = true, defaultValue = "0.0")
	protected BigDecimal fit;
	@XmlElement(name = "SocialSecurity", required = true, defaultValue = "0.0")
	protected BigDecimal socialSecurity;
	@XmlElement(name = "Medicare", required = true, defaultValue = "0.0")
	protected BigDecimal medicare;
	@XmlElement(name = "SIT", required = true, defaultValue = "0.0")
	protected BigDecimal sit;
	@XmlElement(name = "Deductions", required = true, nillable = true)
	protected List<DedeuctionType> deductions;
	@XmlElement(name = "NetPay", required = true, defaultValue = "0.0")
	protected BigDecimal netPay;

	/**
	 * Gets the value of the monthlyGrossPay property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getMonthlyGrossPay() {
		return monthlyGrossPay;
	}

	/**
	 * Sets the value of the monthlyGrossPay property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setMonthlyGrossPay(BigDecimal value) {
		this.monthlyGrossPay = value;
	}

	/**
	 * Gets the value of the fit property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getFIT() {
		return fit;
	}

	/**
	 * Sets the value of the fit property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setFIT(BigDecimal value) {
		this.fit = value;
	}

	/**
	 * Gets the value of the socialSecurity property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getSocialSecurity() {
		return socialSecurity;
	}

	/**
	 * Sets the value of the socialSecurity property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setSocialSecurity(BigDecimal value) {
		this.socialSecurity = value;
	}

	/**
	 * Gets the value of the medicare property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getMedicare() {
		return medicare;
	}

	/**
	 * Sets the value of the medicare property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setMedicare(BigDecimal value) {
		this.medicare = value;
	}

	/**
	 * Gets the value of the sit property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getSIT() {
		return sit;
	}

	/**
	 * Sets the value of the sit property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setSIT(BigDecimal value) {
		this.sit = value;
	}

	/**
	 * Gets the value of the deductions property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deductions property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeductions().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DedeuctionType }
	 */
	public List<DedeuctionType> getDeductions() {
		if (deductions == null) {
			deductions = new ArrayList<DedeuctionType>();
		}
		return this.deductions;
	}

	/**
	 * Gets the value of the netPay property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getNetPay() {
		return netPay;
	}

	/**
	 * Sets the value of the netPay property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setNetPay(BigDecimal value) {
		this.netPay = value;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PayrollResponse [monthlyGrossPay=");
		builder.append(monthlyGrossPay);
		builder.append(", fit=");
		builder.append(fit);
		builder.append(", socialSecurity=");
		builder.append(socialSecurity);
		builder.append(", medicare=");
		builder.append(medicare);
		builder.append(", sit=");
		builder.append(sit);
		builder.append(", deductions=");
		builder.append(deductions);
		builder.append(", netPay=");
		builder.append(netPay);
		builder.append("]");
		return builder.toString();
	}

}
