//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

package com.epayroll.ws.pojo;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

/**
 * <p>
 * Java class for anonymous complex type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EmployeeName" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="TaxYear">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}integer">
 *               &lt;pattern value="[1-9][0-9][0-9][0-9]"/>
 *               &lt;minInclusive value="1990"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="State" type="{http://www.w3.org/2001/XMLSchema}token"/>
 *         &lt;element name="GrossPay" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="PayFrequency" type="{http://www.i-techsoftware.com/vjs-payroll}PayFrequencyType"/>
 *         &lt;element name="FederalFilingStatus" type="{http://www.i-techsoftware.com/vjs-payroll}FederalFilingStatusType"/>
 *         &lt;element name="NoOfAllowance" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="AdditionalFederalWithholding" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="IsExempted" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="FilingStatus" type="{http://www.i-techsoftware.com/vjs-payroll}FilingStatusType"/>
 *         &lt;element name="PersonalExemptions" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="AdditionalExemptions" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="AdditionalStateWithholding" type="{http://www.i-techsoftware.com/vjs-payroll}DecimalType"/>
 *         &lt;element name="Deductions" type="{http://www.i-techsoftware.com/vjs-payroll}DedeuctionType" maxOccurs="10"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "employeeName", "taxYear", "state", "grossPay", "payFrequency",
		"federalFilingStatus", "noOfAllowance", "additionalFederalWithholding", "isExempted",
		"filingStatus", "personalExemptions", "additionalExemptions", "additionalStateWithholding",
		"deductions" })
@XmlRootElement(name = "PayrollRequest")
public class PayrollRequest {

	@XmlElement(name = "EmployeeName", required = true, defaultValue = "", nillable = true)
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String employeeName;
	@XmlElement(name = "TaxYear", required = true, defaultValue = "2013")
	protected BigInteger taxYear;
	@XmlElement(name = "State", required = true, defaultValue = "Virginia")
	@XmlJavaTypeAdapter(CollapsedStringAdapter.class)
	@XmlSchemaType(name = "token")
	protected String state;
	@XmlElement(name = "GrossPay", required = true)
	protected BigDecimal grossPay;
	@XmlElement(name = "PayFrequency", required = true, defaultValue = "Weekly")
	protected PayFrequencyType payFrequency;
	@XmlElement(name = "FederalFilingStatus", required = true, defaultValue = "Single")
	protected FederalFilingStatusType federalFilingStatus;
	@XmlElement(name = "NoOfAllowance", required = true, defaultValue = "0")
	protected BigDecimal noOfAllowance;
	@XmlElement(name = "AdditionalFederalWithholding", required = true, defaultValue = "0.0")
	protected BigDecimal additionalFederalWithholding;
	@XmlElement(name = "IsExempted", defaultValue = "false")
	protected boolean isExempted;
	@XmlElement(name = "FilingStatus", required = true, defaultValue = "Regular")
	protected FilingStatusType filingStatus;
	@XmlElement(name = "PersonalExemptions", required = true, defaultValue = "0.0")
	protected BigDecimal personalExemptions;
	@XmlElement(name = "AdditionalExemptions", required = true, defaultValue = "0.0")
	protected BigDecimal additionalExemptions;
	@XmlElement(name = "AdditionalStateWithholding", required = true, defaultValue = "0.0")
	protected BigDecimal additionalStateWithholding;
	@XmlElement(name = "Deductions", required = true, nillable = true)
	protected List<DedeuctionType> deductions;

	/**
	 * Gets the value of the employeeName property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getEmployeeName() {
		return employeeName;
	}

	/**
	 * Sets the value of the employeeName property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setEmployeeName(String value) {
		this.employeeName = value;
	}

	/**
	 * Gets the value of the taxYear property.
	 * 
	 * @return possible object is {@link BigInteger }
	 */
	public BigInteger getTaxYear() {
		return taxYear;
	}

	/**
	 * Sets the value of the taxYear property.
	 * 
	 * @param value
	 *            allowed object is {@link BigInteger }
	 */
	public void setTaxYear(BigInteger value) {
		this.taxYear = value;
	}

	/**
	 * Gets the value of the state property.
	 * 
	 * @return possible object is {@link String }
	 */
	public String getState() {
		return state;
	}

	/**
	 * Sets the value of the state property.
	 * 
	 * @param value
	 *            allowed object is {@link String }
	 */
	public void setState(String value) {
		this.state = value;
	}

	/**
	 * Gets the value of the grossPay property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getGrossPay() {
		return grossPay;
	}

	/**
	 * Sets the value of the grossPay property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setGrossPay(BigDecimal value) {
		this.grossPay = value;
	}

	/**
	 * Gets the value of the payFrequency property.
	 * 
	 * @return possible object is {@link PayFrequencyType }
	 */
	public PayFrequencyType getPayFrequency() {
		return payFrequency;
	}

	/**
	 * Sets the value of the payFrequency property.
	 * 
	 * @param value
	 *            allowed object is {@link PayFrequencyType }
	 */
	public void setPayFrequency(PayFrequencyType value) {
		this.payFrequency = value;
	}

	/**
	 * Gets the value of the federalFilingStatus property.
	 * 
	 * @return possible object is {@link FederalFilingStatusType }
	 */
	public FederalFilingStatusType getFederalFilingStatus() {
		return federalFilingStatus;
	}

	/**
	 * Sets the value of the federalFilingStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link FederalFilingStatusType }
	 */
	public void setFederalFilingStatus(FederalFilingStatusType value) {
		this.federalFilingStatus = value;
	}

	/**
	 * Gets the value of the noOfAllowance property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getNoOfAllowance() {
		return noOfAllowance;
	}

	/**
	 * Sets the value of the noOfAllowance property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setNoOfAllowance(BigDecimal value) {
		this.noOfAllowance = value;
	}

	/**
	 * Gets the value of the additionalFederalWithholding property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getAdditionalFederalWithholding() {
		return additionalFederalWithholding;
	}

	/**
	 * Sets the value of the additionalFederalWithholding property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setAdditionalFederalWithholding(BigDecimal value) {
		this.additionalFederalWithholding = value;
	}

	/**
	 * Gets the value of the isExempted property.
	 */
	public boolean isIsExempted() {
		return isExempted;
	}

	/**
	 * Sets the value of the isExempted property.
	 */
	public void setIsExempted(boolean value) {
		this.isExempted = value;
	}

	/**
	 * Gets the value of the filingStatus property.
	 * 
	 * @return possible object is {@link FilingStatusType }
	 */
	public FilingStatusType getFilingStatus() {
		return filingStatus;
	}

	/**
	 * Sets the value of the filingStatus property.
	 * 
	 * @param value
	 *            allowed object is {@link FilingStatusType }
	 */
	public void setFilingStatus(FilingStatusType value) {
		this.filingStatus = value;
	}

	/**
	 * Gets the value of the personalExemptions property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getPersonalExemptions() {
		return personalExemptions;
	}

	/**
	 * Sets the value of the personalExemptions property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setPersonalExemptions(BigDecimal value) {
		this.personalExemptions = value;
	}

	/**
	 * Gets the value of the additionalExemptions property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getAdditionalExemptions() {
		return additionalExemptions;
	}

	/**
	 * Sets the value of the additionalExemptions property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setAdditionalExemptions(BigDecimal value) {
		this.additionalExemptions = value;
	}

	/**
	 * Gets the value of the additionalStateWithholding property.
	 * 
	 * @return possible object is {@link BigDecimal }
	 */
	public BigDecimal getAdditionalStateWithholding() {
		return additionalStateWithholding;
	}

	/**
	 * Sets the value of the additionalStateWithholding property.
	 * 
	 * @param value
	 *            allowed object is {@link BigDecimal }
	 */
	public void setAdditionalStateWithholding(BigDecimal value) {
		this.additionalStateWithholding = value;
	}

	/**
	 * Gets the value of the deductions property.
	 * <p>
	 * This accessor method returns a reference to the live list, not a
	 * snapshot. Therefore any modification you make to the returned list will
	 * be present inside the JAXB object. This is why there is not a
	 * <CODE>set</CODE> method for the deductions property.
	 * <p>
	 * For example, to add a new item, do as follows:
	 * 
	 * <pre>
	 * getDeductions().add(newItem);
	 * </pre>
	 * <p>
	 * Objects of the following type(s) are allowed in the list
	 * {@link DedeuctionType }
	 */
	public List<DedeuctionType> getDeductions() {
		if (deductions == null) {
			deductions = new ArrayList<DedeuctionType>();
		}
		return this.deductions;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("PayrollRequest [employeeName=");
		builder.append(employeeName);
		builder.append(", taxYear=");
		builder.append(taxYear);
		builder.append(", state=");
		builder.append(state);
		builder.append(", grossPay=");
		builder.append(grossPay);
		builder.append(", payFrequency=");
		builder.append(payFrequency);
		builder.append(", federalFilingStatus=");
		builder.append(federalFilingStatus);
		builder.append(", noOfAllowance=");
		builder.append(noOfAllowance);
		builder.append(", additionalFederalWithholding=");
		builder.append(additionalFederalWithholding);
		builder.append(", isExempted=");
		builder.append(isExempted);
		builder.append(", filingStatus=");
		builder.append(filingStatus);
		builder.append(", personalExemptions=");
		builder.append(personalExemptions);
		builder.append(", additionalExemptions=");
		builder.append(additionalExemptions);
		builder.append(", additionalStateWithholding=");
		builder.append(additionalStateWithholding);
		builder.append(", deductions=");
		builder.append(deductions);
		builder.append("]");
		return builder.toString();
	}

}
