//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.02.12 at 10:26:30 AM EST 
//

package com.epayroll.ws.pojo;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for Type.
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * <p>
 * 
 * <pre>
 * &lt;simpleType name="Type">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="% of Gross Pay"/>
 *     &lt;enumeration value="% of Net Pay"/>
 *     &lt;enumeration value="$ Fixed Amount"/>
 *     &lt;enumeration value="$ Hourly Rate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "Type")
@XmlEnum
public enum Type {

	@XmlEnumValue("% of Gross Pay")
	OF_GROSS_PAY("% of Gross Pay"), @XmlEnumValue("% of Net Pay")
	OF_NET_PAY("% of Net Pay"), @XmlEnumValue("$ Fixed Amount")
	$_FIXED_AMOUNT("$ Fixed Amount"), @XmlEnumValue("$ Hourly Rate")
	$_HOURLY_RATE("$ Hourly Rate");
	private final String value;

	Type(String v) {
		value = v;
	}

	public String value() {
		return value;
	}

	public static Type fromValue(String v) {
		for (Type c : Type.values()) {
			if (c.value.equals(v)) {
				return c;
			}
		}
		throw new IllegalArgumentException(v);
	}

}
